config/routes.rb
Rails.application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => "log_out"
  get 'log_in' => 'sessions#new', :as => 'log_in'

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :sessions
  resources :users 
  resources :urls

  

end

app/models/url.rb
class Url < ActiveRecord::Base
	
	belongs_to :user
	before_save :add_short_url
	
	def add_short_url 
		self.shortened_url = "http://jag.ly/#{Array.new(5){rand(36).to_s(36)}.join}"
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :urls

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end 
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
  	@urls = Url.all
  		session[:user_id] = user.id
  		render "urls/index", :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
 		end
 	end
 
 	def destroy
 		session[:user_id] = nil
 		redirect_to root_url, :notice => "Logged out!"
 	end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	def index
		@urls = Url.all
	end

	def new
	end

	
	def create
		 @url = Url.new(url_params)
		 @url
		 @url.save
		 redirect_to @url
	end

	def show
		@url = Url.find(params[:id])
	end

	private
		def url_params
			params.require(:url).permit(:original_address, :shortened_url)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to "urls/new", :notice => "Signed up!"
		else
			render "new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

  

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>



  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="text-center">
	<% if current_user %>
		Logged in as <%= current_user.email %>
		<%=link_to "Log out", log_out_path %>
	<% else %>
		<%= link_to "Sign up", sign_up_path %> or <%= link_to "log in", log_in_path %>
	<%end %>


<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
	</div>
</div>
<%= yield %>




</div>
</body>
</html>

app/views/urls/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
      <h2 class="text-center">
      <%= image_tag "58041639.jpg" %>
      </h2>
     
    </div>
    
</div>


<div class="container">
  <div class="col-md-12">
    <div class="text-center">
    <%= form_for :url, url: urls_path do |f| %>
  <p>
    <%= f.label :original_address %><br>
    <%= f.text_field :original_address %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

    </div>
  </div>
</div>



<div class="container">
  <div class="col-md-12">
    <div class="text-center">

  <h3>A list of all your URLs</h3>
    <% @urls.each do |link| %>
    <ul class="text-center">
    
    <li><a href="<%link.original_address%>"> <%=link.original_address%></a></li>
      <li><a href="/<%=link.shortened_url%>"> <%=link.shortened_url%> </a>
      </li><br>
    </ul>
    <% end %>

    </div>
  </div>
</div>

app/views/urls/new.html.erb
<h1>Shorten your URL here</h1>

<%= form_for :url, url: urls_path do |f| %>
  <p>
    <%= f.label :original_address %><br>
    <%= f.text_field :original_address %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/urls/show.html.erb
<p>
  <strong>URL:</strong>
  <a href="<%= @url.original_address %>"><%= @url.original_address %>"</a> 
</p>
 
<p>
  <strong>Shortened Url:</strong>
   <a href="<%= @url.original_address%>"><%= @url.shortened_url %></a> 
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello there...</h1>
<p>Find me in app/views/welcome/index.html.erb</p>